#!/bin/sh /etc/rc.common

START=98
STOP=10
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/lib/easymanet/led-status.sh
    procd_set_param env EASYMANET_LED_LOG=/var/log/easymanet-led-status.log
    procd_set_param respawn 10 5 0
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
