#!/bin/sh /etc/rc.common

START=97
STOP=10
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/lib/easymanet/display-status.sh
    procd_set_param env EASYMANET_DISPLAY_LOG=/var/log/easymanet-display-status.log
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
